language: node_js
node_js:
- 6.10.3
- 8.0.0
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash # until yarn is
- export PATH=$HOME/.yarn/bin:$PATH                 # pre-installed
script:
- node bin/ci.js
env:
  matrix:
  - TEST_TYPE=lint_and_test_unit
  - TEST_TYPE=integration_test
  - TEST_TYPE=test_create_project_npm
  - TEST_TYPE=test_create_project_yarn
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: paulo@ragonha.me
  api_key:
    secure: uwtKe6c+QPSOi7QLCGmVw5cIxl4XDAhaxVWKmRT/GA5CUALjY7ZY1i9Kn6mjcIcvW9HxATU51BASSfq3otWoSJnJB+J3E0kMHJTDW5JMYbQoeu0jRz6ny/FnQoNGvtd3GEAxBkRLCmE0bUzA+1hY+ZxTF/k+zcn2jWcdZk6VGsE=
  on:
    tags: true
    repo: saguijs/sagui
